### PR TITLE
Adds basic support for overriding templates

### PR DESCRIPTION
**Pull request by naps62**
When using this widget I was having trouble customizing the layout of each element. Overriding CSS is fine for more basic cases, but once I need to customize the markup (or even adding custom elements to each element), being traped in the default templates makes it much harder

So I thought of doing this directly on this widget, which is what this PR is for
it adds 3 options to the constructor, where I can override each template that is being used in the widget

I'm not really sure you guys want something like this on this widget, or if it's just intended to be used as it is. There are also a few problems, which I tried to explain in the documentation, but would require a larger work on the view code to get sorted out

### CODE REVIEW

**Comment by colinmacdonald** [comment]
I definitely see the usefulness of such an option but it concerns me that future versions of the widget with changes to the view/default templates could break widgets using the custom template options. Ultimately it would have to be left up to the developer to ensure the version of the widget that they are using will work with their custom template.

That being said, I'll take a closer look at the PR over the weekend, thanks for the contribution!

**Comment by naps62** [comment]
Yes, I also had the same concerns, but could not think an easy way to go around that, except for placing a warning in the docs (which isn't a perfect idea, either)

But I'm thinking of forking this to make a more specific widget, for the particular app I'm developing. Since this was one of the things I needed, I just thought of starting there and make the PR in case it was an interesting feature for you guys

**Comment by colinmacdonald** [comment]
It's an interesting feature that makes the widget really customizable and this is really the best way to do it.

I alluded to the WebRTC widget really being just a view driven by GoRTC events in #15. It sounds like you have big plans for building a custom WebRTC app and you could just continue working with the WebRTC widget fork. Alternatively, you may find it easier to build a more specific app using the GoRTC library in the same way the WebRTC widget leverages GoRTC.

**Comment by naps62** [comment]
Yes, i know about the GoRTC layer. Even played around a bit with it in a test application, before settling with the widget. But I have some urgency in getting the MVP done in the next couple of weeks, so the widget was the way to go for now, even if I end up switching later

**Comment by colinmacdonald** [comment]
To make this feature work either the view can't make assumptions about the template or the template has to be validated when passed as an option. I will look into doing this in the near future, we can leave the PR open until then.

**Pull request closed without merging**
